### ISSUE TITLE
Some files use programming bad practices.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [proudloyaltier/timedia#10]
Some of the HTML files are missing a head tag, a html tag, and a DOCTYPE tag. Sure, this works anyways, but it's really bad practice and may not be compatible with all browsers.
Using `localStorage.<key>` to set or retrieve values is bad practice. Use `localStorage.getItem` to get the value and `localStorage.setItem` to set it.

@proudloyaltier

**Comment by proudloyaltier** [comment]
Which ones HTML files?, I know the localStorage.<key> issue, I will fix eventually. @Legend-of-iPhoenix

**Comment by Legend-of-iPhoenix** [comment]
- https://github.com/proudloyaltier/timedia/blob/gh-pages/index.html
- https://github.com/proudloyaltier/timedia/blob/gh-pages/beta/logout.html

**Comment by proudloyaltier** [comment]
I know, those two are not actually meant to be HTML files, they are just redirecting you and clearing localStorage

**Comment by proudloyaltier** [comment]
I will keep it open but it isn't very high on my list of things to do

**Comment by Legend-of-iPhoenix** [comment]
They are very clearly meant to be html files, they are `.html`.

:P

**Comment by proudloyaltier** [comment]
I know, we just can't do it in pure js, you can't make a website in a `.js` file since it will just show the source code

**Comment by proudloyaltier** [comment]
Fixing today, when I get to a computer
