### ISSUE TITLE
You are spewing commits up the wazzoo.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [proudloyaltier/timedia#16]
Having a lot of commits isn't good. It doesn't show dedication, skill, or importance. Raither, it shows quite the opposite.

The term "commit" is short for "commitment", and that's exactly what it should be. You are *commiting* to making that change. You aren't going to revert it immediately, because you have tested it already and know the outcome.

Did you know that your repository is 18-ish MB, with just the files. That's mostly because you have a bunch of images, but that's not the problem. The problem is the extra couple of megabytes of git information layered on top of this.

Minimizing your commits makes it easier for others to help. If there's less crap for me to dig through, I can help you with your project more. This goes along with giving each commit a short, descriptive name. If you look at the commit history of my UniChatDemo repo, you will see lots of "spam" commits. Over on my much more recent iChat repository, you will notice that I've tried to give each commit a name. This takes me an extra two seconds to do, and it could save someone else trying to figure out what your code is doing much more than that.

Keeping your code well-formatted and up to current specifications is also extremely important. Not only does it maximize readability, but it also saves you and others time later. Sure, Chrome might be nice and surround your lonesome <script> tag in the required <body> and <html> elements, but you should not rely on this.

**Comment by proudloyaltier** [comment]
Copyright 2018 TiMedia. all rights reserved

**Comment by Legend-of-iPhoenix** [comment]
[I'm done](https://www.cemetech.net/forum/viewtopic.php?p=270446#270446). @proudloyaltier

**Comment by PeterTillema** [comment]
That's not the way to respond to someone who's helping you, nor the right way to close an issue.

**Comment by proudloyaltier** [comment]
I know that
