### ISSUE TITLE
Your security still sucks.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [proudloyaltier/timedia#18]
Before you rage at me for wrecking your DB (which I did), here, have a backup I made. It includes files I shouldn't have access to: [backup](https://github.com/proudloyaltier/timedia/files/2609497/json.json.zip)

I hope I got it all. I think I did, because I did a pretty thorough automated scrape.

I effectively was able to escalate my account privileges to the level of any user by doing `localStorage.name = localStorage.access = "hymenopus";` in the console. (I'm using `hymenopus` as an example)

I could then delete files, create files, and send messages as if I was that user. 

A more secure way would be to check the email of the user, because only one user can have any specific email. Checking the `displayName` is bad, anyone can change that.

You should also beef up your access and security rules. Certain weaknesses let me change or delete most files.

Some other things:
- Your file upload only checks file type on the JS side, maybe have a way of checking type on the firebase side.
- I used that to upload a very large file. Enforce upload size and rate limits.
- this:
<img width="1186" alt="screen shot 2018-11-22 at 8 27 08 pm" src="https://user-images.githubusercontent.com/32944537/48925995-c6f1ae00-ee97-11e8-8b85-d2fecbb66cf9.png">

**Comment by CerebralDatabank** [comment]
N I C E

**Comment by proudloyaltier** [comment]
You also deleted all of my files, I hope you have a backup

**Comment by proudloyaltier** [comment]
Where is our security checker you forced? Was it the home.js one? If yes, I have a fix, just didn't commit

**Comment by proudloyaltier** [comment]
Also, the reason the security is so bad is that I wrote most of this website before I knew about firebase auth, we used another system (it was horrible) and switching to firebase auth we tried to keep as much as possible intact

**Comment by proudloyaltier** [comment]
Should I try and re-create the entire system for firebase auth, without a localStorage.name or localStorage.access?

**Comment by Legend-of-iPhoenix** [comment]
Probably. Only check the email- check both the domain (@timediatied.com) and the username in your rules.

I think I thought of a new vulnerability, though, I'll test it. I won't delete any files this time :)

**Comment by proudloyaltier** [comment]
Which vulnerability.  Do you mean to access data check both the email (with @timediatied.com) in the firebase rule?

**Comment by proudloyaltier** [comment]
Could I have a localStorage.name, just not used for auth, just for saving tiles to a certain folder

**Comment by proudloyaltier** [comment]
Did you glitch test work

**Comment by proudloyaltier** [comment]
Can you make a pull request with a fix of some kind, I am not good enough at firebase (I tried without success)

**Comment by proudloyaltier** [comment]
Does the first glitch still work with the latest commits

**Comment by proudloyaltier** [comment]
Okay, I restructured the database, should be secure now (its checking by email in the security rules)

**Comment by proudloyaltier** [comment]
Tell me if otherwise, but I think I fixed this issue
