### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by mateoconlechuga** [proudloyaltier/timedia#19]
This site is ridiculous. Links are broken, none of the editing things work correctly, it pops up with random notifications and is essentially worthless.

What is the purpose of this site? Is it just a testing area for you to try things?

**Comment by luca1s** [comment]
Nope, its in development and might be unusable

**Comment by phyllocrania** [comment]
Also, the reason the links are broken for you is that the creation of new accounts is whats broken

**Comment by luca1s** [comment]
Actually, links are broken is valid.  Could you tell me which links? @mateoconlechuga

**Comment by luca1s** [comment]
Also, our beta testers had no issues a day ago, so idk wuts happening. Is there any console log?

EDIT: Just tested again, still working.

**Comment by proudloyaltier** [comment]
I think I fixed some things, so yeah, closing, I'll reopen if our beta testers discover anything
