### ISSUE TITLE
All user data (save passwords) available to everyone.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [proudloyaltier/timedia#6]
Your data is entirely available in an unencrypted form to admins and pretty much anyone.

You should seriously check out firebase security rules. It is really, really important.

[Your entire, publicly-available database, courtesy of Firebase.](http://bit.ly/2I0X3tw)

**Comment by proudloyaltier** [comment]
Ha Ha (admins, otherwise known as me :P), fixing now
