### ISSUE TITLE
You should not be using a script to disable the console.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [proudloyaltier/timedia#7]
- The script is easily bypassed.
- If you need to rely on this script, you have huge problems.
- The whole concept is fundamentally flawed.
- It interferes with the open-source-ness of the whole site.
- If I can't see what the page is doing, how can I trust the webpage?
- If someone is actually going to try and attack your webpage (and have the skills and tools to do it), is a little script disabling the chrome console *really* going to stop them?
Check PR #8 to fix this.

**Comment by proudloyaltier** [comment]
Okay, will do soon

**Comment by Legend-of-iPhoenix** [comment]
Only close issues when they are fixed, @proudloyaltier, they are supposed to remind you :)

**Comment by proudloyaltier** [comment]
Okay, I am fixing one more security glitch that was quite huge and after that, I will close the issue, and merge

**Comment by proudloyaltier** [comment]
Done
